In [1]:
# Data Manipulation
import pandas as pd
import numpy as np

# Regular Expressions
import re

# String Operations
import string

# Natural Language Processing
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
resume_df = pd.read_csv("../data/processed/resume_cleaned.csv")

In [4]:
resume_df.head()

,ID,Resume_str,Resume_html,Category,Resume_Length
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR,5442
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR,5572
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR,7720
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR,2855
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR,9172

In [5]:
print("Shape of Dataset:")
print(resume_df.shape)

print("\nColumns:")
print(resume_df.columns)

print("\nFirst Resume:")
print(resume_df["Resume_str"][0][:500])

Shape of Dataset:
(2484, 5)

Columns:
Index(['ID', 'Resume_str', 'Resume_html', 'Category', 'Resume_Length'], dtype='object')

First Resume:
         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-task

In [6]:
resume_df.dtypes

ID                int64
Resume_str       object
Resume_html      object
Category         object
Resume_Length     int64
dtype: object

In [7]:
resume_df["Clean_Resume"] = resume_df["Resume_str"]

In [8]:
resume_df[["Resume_str", "Clean_Resume"]].head()

,Resume_str,Clean_Resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1,"HR SPECIALIST, US HR OPERATIONS ...","HR SPECIALIST, US HR OPERATIONS ..."
2,HR DIRECTOR Summary Over 2...,HR DIRECTOR Summary Over 2...
3,HR SPECIALIST Summary Dedica...,HR SPECIALIST Summary Dedica...
4,HR MANAGER Skill Highlights ...,HR MANAGER Skill Highlights ...

In [9]:
# Create Lemmatizer
lemmatizer = WordNetLemmatizer()

# English Stopwords
stop_words = set(stopwords.words("english"))

print("Total Stopwords:", len(stop_words))

Total Stopwords: 198

In [10]:
def clean_resume(text):

    # Convert to string
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove phone numbers
    text = re.sub(r'\+?\d[\d\s\-\(\)]{8,}\d', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [11]:
sample = resume_df["Resume_str"][0]

print("Original Resume:\n")
print(sample[:500])

print("\n" + "="*80)

cleaned = clean_resume(sample)

print("\nCleaned Resume:\n")
print(cleaned[:500])

Original Resume:

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-task

================================================================================

Cleaned Resume:

hr administratormarketing associate hr administrator summary dedicated customer service manager with years of experience in hospitality and customer service management respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multitasker client relations specialist accomplishments missouri d

In [12]:
resume_df["Clean_Resume"] = resume_df["Resume_str"].apply(clean_resume)

In [13]:
resume_df.to_csv(
    "../data/processed/resume_text_cleaned.csv",
    index=False
)

In [14]:
import os

os.path.exists("../data/processed/resume_text_cleaned.csv")

True

In [15]:
def preprocess_text(text):

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    # Join back into a sentence
    processed_text = " ".join(tokens)

    return processed_text

In [16]:
sample = resume_df["Clean_Resume"][0]

print("Before Processing:\n")
print(sample[:500])

print("\n" + "="*80)

processed = preprocess_text(sample)

print("\nAfter Processing:\n")
print(processed[:500])

Before Processing:

hr administratormarketing associate hr administrator summary dedicated customer service manager with years of experience in hospitality and customer service management respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multitasker client relations specialist accomplishments missouri d

================================================================================

After Processing:

hr administratormarketing associate hr administrator summary dedicated customer service manager year experience hospitality customer service management respected builder leader customerfocused team strives instill shared enthusiastic commitment customer service highlight focused customer satisfaction team management marketing savvy conflict resolution technique training development skilled multitasker client relation specialist accomplishment missouri dot supervisor training certification certif

Words like the, is, of, and, with will be removed.

In [17]:
resume_df["Processed_Resume"] = resume_df["Clean_Resume"].apply(preprocess_text)

In [18]:
resume_df[
    ["Clean_Resume", "Processed_Resume"]
].head()

,Clean_Resume,Processed_Resume
0,hr administratormarketing associate hr adminis...,hr administratormarketing associate hr adminis...
1,hr specialist us hr operations summary versati...,hr specialist u hr operation summary versatile...
2,hr director summary over years experience in r...,hr director summary year experience recruiting...
3,hr specialist summary dedicated driven and dyn...,hr specialist summary dedicated driven dynamic...
4,hr manager skill highlights hr skills hr depar...,hr manager skill highlight hr skill hr departm...

In [19]:
print("Original:\n")
print(resume_df["Resume_str"][0][:500])

print("\n" + "="*100)

print("\nProcessed:\n")
print(resume_df["Processed_Resume"][0][:500])

Original:

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-task

====================================================================================================

Processed:

hr administratormarketing associate hr administrator summary dedicated customer service manager year experience hospitality customer service management respected builder leader customerfocused team strives instill shared enthusiastic commitment customer service highlight focused customer satisfaction team management marketing savvy conflict resolution technique training development skilled multitasker client relation specialist accomplishment missouri dot supervisor training certification certif

In [20]:
empty = resume_df["Processed_Resume"].apply(len) == 0

print("Empty Resumes:", empty.sum())

Empty Resumes: 1

In [21]:
resume_df.to_csv(
    "../data/processed/resume_processed.csv",
    index=False
)

In [22]:
import os

print(
    os.path.exists("../data/processed/resume_processed.csv")
)

True

In [23]:
resume_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                2484 non-null   int64
 1   Resume_str        2484 non-null   object
 2   Resume_html       2484 non-null   object
 3   Category          2484 non-null   object
 4   Resume_Length     2484 non-null   int64
 5   Clean_Resume      2484 non-null   object
 6   Processed_Resume  2484 non-null   object
dtypes: int64(2), object(5)
memory usage: 136.0+ KB

In [24]:
# Create Lemmatizer
lemmatizer = WordNetLemmatizer()

# Load English Stopwords
stop_words = set(stopwords.words("english"))

print("Total Stopwords:", len(stop_words))

Total Stopwords: 198

In [25]:
# Create a new column for preprocessing
resume_df["Clean_Resume"] = resume_df["Resume_str"]

# Display the first few rows
resume_df[["Resume_str", "Clean_Resume"]].head()

,Resume_str,Clean_Resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1,"HR SPECIALIST, US HR OPERATIONS ...","HR SPECIALIST, US HR OPERATIONS ..."
2,HR DIRECTOR Summary Over 2...,HR DIRECTOR Summary Over 2...
3,HR SPECIALIST Summary Dedica...,HR SPECIALIST Summary Dedica...
4,HR MANAGER Skill Highlights ...,HR MANAGER Skill Highlights ...

In [26]:
def clean_resume(text):

    # Convert to string
    text = str(text)

    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove phone numbers
    text = re.sub(r'\+?\d[\d\s\-\(\)]{8,}\d', ' ', text)

    # Remove numbers
    text = re.sub(r'\d+', ' ', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [27]:
sample = resume_df["Resume_str"][0]

print("Original Resume:\n")
print(sample[:500])

print("\n" + "="*80)

cleaned = clean_resume(sample)

print("\nCleaned Resume:\n")
print(cleaned[:500])

Original Resume:

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-task

================================================================================

Cleaned Resume:

hr administratormarketing associate hr administrator summary dedicated customer service manager with years of experience in hospitality and customer service management respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multitasker client relations specialist accomplishments missouri d

In [28]:
resume_df["Clean_Resume"] = resume_df["Resume_str"].apply(clean_resume)

In [29]:
resume_df[["Resume_str", "Clean_Resume"]].head()

,Resume_str,Clean_Resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administratormarketing associate hr adminis...
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist us hr operations summary versati...
2,HR DIRECTOR Summary Over 2...,hr director summary over years experience in r...
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven and dyn...
4,HR MANAGER Skill Highlights ...,hr manager skill highlights hr skills hr depar...

In [30]:
def preprocess_text(text):

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    # Join tokens
    processed_text = " ".join(tokens)

    return processed_text

In [31]:
sample = resume_df["Clean_Resume"][0]

processed = preprocess_text(sample)

print(processed[:500])

hr administratormarketing associate hr administrator summary dedicated customer service manager year experience hospitality customer service management respected builder leader customerfocused team strives instill shared enthusiastic commitment customer service highlight focused customer satisfaction team management marketing savvy conflict resolution technique training development skilled multitasker client relation specialist accomplishment missouri dot supervisor training certification certif

In [32]:
resume_df["Processed_Resume"] = resume_df["Clean_Resume"].apply(preprocess_text)

In [33]:
resume_df[
    ["Clean_Resume", "Processed_Resume"]
].head()

,Clean_Resume,Processed_Resume
0,hr administratormarketing associate hr adminis...,hr administratormarketing associate hr adminis...
1,hr specialist us hr operations summary versati...,hr specialist u hr operation summary versatile...
2,hr director summary over years experience in r...,hr director summary year experience recruiting...
3,hr specialist summary dedicated driven and dyn...,hr specialist summary dedicated driven dynamic...
4,hr manager skill highlights hr skills hr depar...,hr manager skill highlight hr skill hr departm...

In [34]:
empty = resume_df["Processed_Resume"].apply(len) == 0

print("Empty Resumes:", empty.sum())

Empty Resumes: 1

In [35]:
resume_df.to_csv(
    "../data/processed/resume_processed.csv",
    index=False
)

In [36]:
resume_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                2484 non-null   int64
 1   Resume_str        2484 non-null   object
 2   Resume_html       2484 non-null   object
 3   Category          2484 non-null   object
 4   Resume_Length     2484 non-null   int64
 5   Clean_Resume      2484 non-null   object
 6   Processed_Resume  2484 non-null   object
dtypes: int64(2), object(5)
memory usage: 136.0+ KB

In [37]:
#identify empty resume     
empty_resumes = resume_df[resume_df["Processed_Resume"].str.strip() == ""]

empty_resumes

,ID,Resume_str,Resume_html,Category,Resume_Length,Clean_Resume,Processed_Resume
656,12632728,,"<div class=""fontsize fontface vmargins hmargin...",BUSINESS-DEVELOPMENT,21,,

In [38]:
empty_index = resume_df[resume_df["Processed_Resume"].str.len() == 0].index

print(resume_df.loc[empty_index, "Resume_str"].values[0])

In [39]:
resume_df = resume_df[resume_df["Processed_Resume"].str.strip() != ""]

In [40]:
print("Dataset Shape:", resume_df.shape)

print("Empty Resumes:",
      (resume_df["Processed_Resume"].str.len() == 0).sum())

Dataset Shape: (2483, 7)
Empty Resumes: 0

In [41]:
resume_df.to_csv(
    "../data/processed/resume_processed.csv",
    index=False
)